# Generated by Django 3.2.3 on 2021-05-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='in_queue',
            field=models.BooleanField(default=True),
        ),
    ]
