# Generated by Django 3.2.3 on 2021-05-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0002_song_in_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='sets',
            field=models.ManyToManyField(related_name='songs', to='hymnal_app.Set'),
        ),
    ]
