# Generated by Django 3.2.3 on 2021-05-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0003_alter_song_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
    ]
