# Generated by Django 3.2.3 on 2021-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0004_song_is_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='list_order',
            new_name='list_order_queue',
        ),
        migrations.AddField(
            model_name='song',
            name='list_order_saved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
