# Generated by Django 3.2.3 on 2021-05-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0005_auto_20210518_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='copy_number',
            field=models.IntegerField(default=0),
        ),
    ]
