# Generated by Django 3.2.3 on 2021-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0006_song_copy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='list_order_queue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='list_order_saved',
            field=models.IntegerField(default=0),
        ),
    ]
