# Generated by Django 3.2.3 on 2021-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hymnal_app', '0007_auto_20210518_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='in_queue',
            field=models.BooleanField(default=False),
        ),
    ]
